"H============ Searching ============"
"Highlight searches by default"
set hlsearch
set showmatch
set incsearch


"============ Tab width ============"
set tabstop=4
set shiftwidth=4
set softtabstop=4
"set expandtab "Makes vim substitute tab character with spaces"
set smartindent
set autoindent
set showbreak=...


"============ Swap files ============"
"No swap files"
set noswapfile
set nobackup
set nowb

"============ Movement ============"
"Move one row instead of one line"
nmap j gj
nmap k gk 

"============ Page width ============"
" This creates an invisible colorcolumn
" set textwidth=80
" hi ColorColumn ctermbg=None
" Text that spans over 80 characters will
" turn red
" hi ColorColumn ctermfg=Red
" execute "set colorcolumn=" . join(range(81,335), ',')

"============ Auto completion ============"
set wildmenu
set wildmode=list:longest,full

"============ Cursor ============"
if has("autocmd")
  au InsertEnter * set cul
  au InsertLeave * set nocul 
endif

set nocompatible

" Pathogen
call pathogen#infect()
call pathogen#helptags()
 
set statusline=%<\ %n:%f\ %m%r%y%=%-35.(line:\ %l\ of\ %L,\ col:\ %c%V\ (%P)%)
filetype plugin indent on
 
" Nerdtree
" autocmd vimenter * NERDTree 
let NERDTreeShowBookmarks=1
let NERDTreeChDirMode=0
let NERDTreeQuitOnOpen=1
let NERDTreeMouseMode=2
let NERDTreeShowHidden=1
let NERDTreeIgnore=['\.pyc','\~$','\.swo$','\.swp$','\.git','\.hg','\.svn','\.bzr']
let NERDTreeKeepTreeInNewTab=1
let g:nerdtree_tabs_open_on_gui_startup=0
autocmd vimenter * if !argc() | NERDTree | endif
map <C-n> :NERDTreeToggle<CR>

" Clang complete
let g:clang_use_library = 1
let g:clang_library_path = '/usr/lib/'
let g:clang_snippets = 1

"========== Theme ============"
if has('unnamedplus')
	set clipboard=unnamedplus
else
	set clipboard=unnamed
endif
"========== Theme ============"
set number
syntax enable
set background=dark
colorscheme solarized

"========== Map ============"
map Q <Nop>

