#!/bin/bash

#eval $(gnome-keyring-daemon --start)
#export GNOME_KEYRING_SOCKET
#export GNOME_KEYRING_PID


eval $(ssh-agent)

# setxkbmap -layout "barber(barborak)" -option &
setxkbmap "se(svdvorak)" &
xmonad
